name: "Lesson 14 - NoSql"

services:
  mongo:
    image: mongo
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      CONNECTION_URL: mongodb://root:root@localhost:27018