apiVersion: v1
kind: Service
metadata:
  name: redis-client
  namespace: default
  labels:
    app: redis-client
spec:
  ports:
    - port: 6379
      name: redis
  clusterIP: None
  selector:
    app: redis-client