plugin: amazon.aws.aws_ec2
regions:
  - eu-north-1
filters:
  tag:Environment: development
keyed_groups:
  - key: tags.Name
    prefix: 'ansible-demo'
hostnames:
  - public_ip_address
variables:
  ansible_user: ubuntu
  ansible_ssh_private_key_file: ../ssh-keys/europe-stockholm-ssh-rsa-keygen.pem