plugin: amazon.aws.aws_ec2
regions:
  - eu-north-1
filters:
  tag:Environment: development
keyed_groups:
  - prefix: tag
    key: tags
hostnames:
  - ip-address
compose:
  ansible_host: public_ip_address
