services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    restart: always
    network_mode: "host"

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./configs/promtail-config.yml:/etc/promtail/promtail-config.yml:ro
      - /var/log/nginx:/var/log/nginx:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/promtail-config.yml
    restart: always
