name: Build and Test

on:
  push:
    branches: [main, staging]
  pull_request:
    types:
      - opened
      - ready_for_review
      - synchronize
      - reopened

concurrency:
  group: build-and-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: ./.github/actions/checkout

      - name: Build Application
        uses: ./.github/actions/build

      - name: Run Tests
        uses: ./.github/actions/test
