- name: Ensure pip3 is installed
  become: yes
  package:
    name: python3-pip
    state: present

- name: Install PyMySQL for Ansible MySQL modules
  become: yes
  pip:
    name: PyMySQL
    executable: pip3

- name: Create database user
  mysql_user:
    name: root
    password: "securePass1"
    login_host: "monitoring-rds.cn6so2sa0mf8.eu-north-1.rds.amazonaws.com"
    login_port: 3306
    login_user: admin
    login_password: "securePass1"
    host: "%"
    state: present